config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tc.urls'))
]

tc/urls.py
from django.urls import path
from . import views

app_name = "tc"

urlpatterns = [
    path('', views.layout_view, name='home'),
    path('introducao/', views.intro_view, name='intro'),
    path('automatos/', views.automatos_view, name='automatos'),
    path('automatosform/', views.automatos_form_view, name='automatosform'),
    path('automatoseditar/<int:automato_id>', views.automatos_editar_view, name='automatoseditar'),
    path('automatosapagar/<int:automato_id>', views.automatos_apagar_view, name='automatosapagar'),
    path('automatosdetalhes/<int:automato_id>', views.automatos_detalhes_view, name='automatosdetalhes'),
    path('automatosseq/<int:automato_id>', views.automatos_seq_view, name='automatosseq'),
    path('maquinas/', views.maquinas_view, name='maquinas'),
    path('maquinasform/', views.maquinas_form_view, name='maquinasform'),
    path('maquinaseditar/<int:maquina_id>', views.maquinas_editar_view, name='maquinaseditar'),
    path('maquinasapagar/<int:maquina_id>', views.maquinas_apagar_view, name='maquinasapagar'),
    path('maquinasdetalhes/<int:maquina_id>', views.maquinas_detalhes_view, name='maquinasdetalhes'),
    path('maquinasseq/<int:maquina_id>', views.maquinas_seq_view, name='maquinasseq'),
]

tc/models.py
from django.db import models

# Create your models here.


class Automato(models.Model):
    descricao = models.CharField(max_length=70)
    estados = models.CharField(max_length=30)
    alfabeto = models.CharField(max_length=10)
    estado_inicial = models.CharField(max_length=1)
    estados_aceitacao = models.CharField(max_length=10)
    tabela_transicao = models.CharField(max_length=30)

class Maquina(models.Model):
    descricao = models.CharField(max_length=70)
    estados = models.CharField(max_length=30)
    alfabeto = models.CharField(max_length=10)
    alfabeto_fita = models.CharField(max_length=10)
    estado_inicial = models.CharField(max_length=1)
    halt_accept = models.CharField(max_length=10)
    halt_reject = models.CharField(max_length=10)
    tabela_transicao = models.CharField(max_length=30)

class Sequencia(models.Model):
    sequencia = models.CharField(max_length=20)

    def __str__(self):
        return self.descricao

tc/forms.py
from django.forms import ModelForm

from .models import Automato, Maquina, Sequencia


class AutomatosForm(ModelForm):
    class Meta:
        model = Automato
        fields = '__all__'

class MaquinasForm(ModelForm):
    class Meta:
        model = Maquina
        fields = '__all__'

class SequenciaForm(ModelForm):
    class Meta:
        model = Sequencia
        fields = '__all__'

tc/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import AutomatosForm, MaquinasForm, SequenciaForm
from .models import Automato, Maquina, Sequencia


# Create your views here.

def layout_view(request):
    return render(request, 'tc/base.html')


def intro_view(request):
    return render(request, 'tc/introducao.html')


def automatos_view(request):
    context = {'automatos': Automato.objects.all()}
    return render(request, 'tc/automatos.html', context)


def automatos_detalhes_view(request, automato_id):

    context = {
               'automato' : Automato.objects.get(pk=automato_id),
               'automato_id': automato_id
               }

    return render(request, 'tc/automatosdetalhes.html', context)


def automatos_form_view(request):
    form = AutomatosForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tc:automatos'))

    context = {'form': form}
    return render(request, 'tc/automatosform.html', context)


def automatos_editar_view(request, automato_id):
    automato = Automato.objects.get(pk=automato_id)
    form = AutomatosForm(request.POST or None, instance=automato)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tc:automatos'))

    context = {'form': form,
               'automato_id': automato_id
               }

    return render(request, 'tc/automatoseditar.html', context)


def automatos_apagar_view(request, automato_id):
    Automato.objects.get(id=automato_id).delete()

    return HttpResponseRedirect(reverse('tc:automatos'))

def automatos_seq_view(request, automato_id):
    resultado = sequencia = None

    if request.POST:
        form = SequenciaForm(request.POST)  # a expressão submetida no formulário é guardada na variável form
        if form.is_valid():
            sequencia = form.cleaned_data['sequencia']
            try:
                for simbolo in sequencia:
                    estado_atual = Automato.tabela_transicao[(estado_atual, simbolo)]

                if estado_atual in Automato.estados_aceitacao:
                    resultado = eval(sequencia)
            except:
                resultado = "Sequencia Inválida"

    form = SequenciaForm(None)

    context = {
        'form': form,
        'resultado': resultado,
        'sequencia': sequencia
    }

    return render(request, 'tc/automatosseq.html', context)

def maquinas_view(request):
    context = {'maquinas': Maquina.objects.all()}
    return render(request, 'tc/maqturing.html', context)

def maquinas_detalhes_view(request, maquina_id):

    context = {
               'maquina' : Maquina.objects.get(pk=maquina_id),
               'maquina_id': maquina_id
               }

    return render(request, 'tc/maqturingdetalhes.html', context)

def maquinas_form_view(request):
    form = MaquinasForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tc:maquinas'))

    context = {'form': form}
    return render(request, 'tc/maqturingform.html', context)

def maquinas_editar_view(request, maquina_id):
    maquina = Maquina.objects.get(pk=maquina_id)
    form = MaquinasForm(request.POST or None, instance=maquina)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tc:maquinas'))

    context = {'form': form,
               'maquina_id': maquina_id
               }

    return render(request, 'tc/maqturingeditar.html', context)

def maquinas_apagar_view(request, maquina_id):
    Maquina.objects.get(id=maquina_id).delete()

    return HttpResponseRedirect(reverse('tc:maquinas'))

def maquinas_seq_view(request, maquina_id):
    resultado = sequencia = None
    if request.POST:
        form = SequenciaForm(request.POST)  # a expressão submetida no formulário é guardada na variável form
        if form.is_valid():
            sequencia = form.cleaned_data['sequencia']
            try:
                for simbolo in sequencia:
                    estado_atual = Maquina.tabela_transicao[(estado_atual, simbolo)]

                if estado_atual in Maquina.halt_accept:
                    resultado = eval(sequencia)
            except:
                resultado = "Sequencia Inválida"

    form = SequenciaForm(None)

    context = {
        'form': form,
        'resultado': resultado,
        'sequencia': sequencia
    }

    return render(request, 'tc/maquinasseq.html', context)

tc/templates/tc/automatos.html
{% extends 'tc/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'tc/base.css' %}">
{% block main %}
<div class="myDiv">
        <h2>Autómatos Finitos Determinísticos (AFD)</h2>
        <br>
        <a href="{% url 'tc:automatosform' %}" class="btn btn-success" >Crie um AFD</a>
        <br><br>
        <h7>Apresentam-se em baixo os autómatos que foram criados </h7>
    <br><br>
</div>
<div class="row">
    <div class="col">
        <div class="myDiv2">
        <h2>Descrição</h2>
            <br>
        {% for automato in automatos %}
            <p>{{ automato.descricao }}</p>
            <nav>
                <a href="{% url 'tc:automatoseditar' automato.id %}" class="btn btn-info">Detalhes</a>
                <a href="{% url 'tc:automatosseq' automato.id %}" class="btn btn-success">Validar Sequencia</a>
                <a href="{% url 'tc:automatoseditar' automato.id %}" class="btn btn-warning">Editar AFD</a>
                <a href="{% url 'tc:automatosapagar' automato.id %}" class="btn btn-danger">Apagar AFD</a>
                <br><br>
            </nav>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

tc/templates/tc/automatosapagar.html
{% extends 'tc/base.html' %}

{% block main %}

{% endblock %}

tc/templates/tc/automatoseditar.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Novo Automato</h3>

    <form action="{% url 'tc:automatoseditar' automato_id %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
         <a href="{% url 'tc:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success">
    </form>


{% endblock %}

tc/templates/tc/automatosform.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Novo Autómato</h3>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <a href="{% url 'tc:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success">
    </form>


{% endblock %}

tc/templates/tc/automatosseq.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Validar Sequencia</h3>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <p>{{ resultado }}</p>
        <a href="{% url 'tc:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Validar" class="btn btn-success">
    </form>


{% endblock %}

tc/templates/tc/base.html
<!DOCTYPE html>
<html lang="">
	<head>
		<meta charset="UTF-8">
    		<title>Website</title>
		{% load static %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'tc/base.css' %}">
	</head>
	<body>
	    <header class="jumbotron text-center">
            <h1>Teoria da Computação</h1>
            <nav>
                <a href="{% url 'tc:intro' %}" class="btn btn-info">Introdução</a>
                <a href="{% url 'tc:automatos' %}" class="btn btn-info">Autómatos</a>
                <a href="{% url 'tc:maquinas' %}" class="btn btn-info">Máquinas de Turing </a>
            </nav>
        </header>
	    <article class="container">
            {% block main %}
	        {% endblock main %}
	    </article>

	</body>
</html>

tc/templates/tc/introducao.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>O que é a teoria da computação?</h3>
    <p>A teoria da computação é um ramo da ciência da computação que trata de problemas <br> que podem ser resolvidos à luz de um modelo, um algoritmo, quão eficientemente o
        <br>conseguem resolver e se sequer o conseguem resolver.</p>
    <br>
    <h3><i>Branches</i> da teoria da computação</h3>
    <p>É possível ainda dividir a area da teoria da computação em três matérias:</p>
    <ul>
        <li><a href="https://en.wikipedia.org/wiki/Finite-state_machine">Autómatos</a></li>
        <li><a href="https://en.wikipedia.org/wiki/Turing_machine">Máquinas de Turing</a></li>
        <li><a href="https://en.wikipedia.org/wiki/Regular_expression">Expressões Regulares</a></li>
    </ul>
{% endblock %}

tc/templates/tc/maqturing.html
{% extends 'tc/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'tc/base.css' %}">
{% block main %}
<div class="myDiv">
        <h2>Máquinas de Turing</h2>
        <br>
        <a href="{% url 'tc:maquinasform' %}" class="btn btn-success" >Crie uma Máquina de Turing</a>
        <br><br>
        <h7>Apresentam-se em baixo as Máquinas que foram criadas </h7>
    <br><br>
</div>
<div class="row">
    <div class="col">
        <div class="myDiv2">
        <h2>Descrição</h2>
            <br>
        {% for maquina in maquinas %}
            <p>{{ maquina.descricao }}</p>
            <nav>
                <a href="{% url 'tc:maquinaseditar' maquina.id %}" class="btn btn-info">Detalhes</a>
                <a href="{% url 'tc:maquinasseq' maquina.id %}" class="btn btn-success">Validar Sequencia</a>
                <a href="{% url 'tc:maquinaseditar' maquina.id %}" class="btn btn-warning">Editar Maquina</a>
                <a href="{% url 'tc:maquinasapagar' maquina.id %}" class="btn btn-danger">Apagar Maquina</a>
                <br><br>
            </nav>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}%}

tc/templates/tc/maqturingapagar.html
{% extends 'tc/base.html' %}

{% block main %}

{% endblock %}

tc/templates/tc/maqturingeditar.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Nova Maquina</h3>

    <form action="{% url 'tc:maquinaseditar' maquina_id %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
         <a href="{% url 'tc:maquinas' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success">
    </form>


{% endblock %}

tc/templates/tc/maqturingform.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Nova Maquina</h3>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <a href="{% url 'tc:maquinas' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success">
    </form>


{% endblock %}

tc/templates/tc/maquinasseq.html
{% extends 'tc/base.html' %}

{% block main %}
    <h3>Validar Sequecia da Maquina</h3>

    <form method="POST" action="">
        {% csrf_token %}

        {{ form.as_p }}
        <p>{{ resultado }}</p>
        <a href="{% url 'tc:maquinas' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Validar" class="btn btn-success">
    </form>


{% endblock %}